from sqlalchemy import Column, Integer, String, Boolean, Float, DateTime, ForeignKey, Enum as SQLEnum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from datetime import datetime
import enum
from app.database.database import Base

class UrgencyLevel(str, enum.Enum):
    """Urgency levels for blood requests"""
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"

class RequestStatus(str, enum.Enum):
    """Status of blood requests"""
    PENDING = "Pending"
    ACTIVE = "Active"
    FULFILLED = "Fulfilled"
    CANCELLED = "Cancelled"

class Donor(Base):
    """Donor model"""
    __tablename__ = "donors"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False, index=True)
    blood_group = Column(String(5), nullable=False, index=True)  # A+, B-, O+, etc.
    lat = Column(Float, nullable=False)  # Latitude
    lng = Column(Float, nullable=False)  # Longitude
    available = Column(Boolean, default=True, nullable=False, index=True)
    last_donation_date = Column(DateTime, nullable=True)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # Relationships
    requests = relationship("Request", back_populates="donor")

class Hospital(Base):
    """Hospital model"""
    __tablename__ = "hospitals"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), nullable=False, index=True)
    location = Column(String(200), nullable=False)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # Relationships
    requests = relationship("Request", back_populates="hospital")

class Request(Base):
    """Blood request model"""
    __tablename__ = "requests"
    
    id = Column(Integer, primary_key=True, index=True)
    hospital_id = Column(Integer, ForeignKey("hospitals.id"), nullable=False, index=True)
    blood_type = Column(String(5), nullable=False, index=True)  # A+, B-, O+, etc.
    urgency = Column(SQLEnum(UrgencyLevel), nullable=False, default=UrgencyLevel.MEDIUM, index=True)
    status = Column(SQLEnum(RequestStatus), nullable=False, default=RequestStatus.PENDING, index=True)
    donor_id = Column(Integer, ForeignKey("donors.id"), nullable=True)  # Assigned donor (if any)
    created_at = Column(DateTime, server_default=func.now(), nullable=False, index=True)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # Relationships
    hospital = relationship("Hospital", back_populates="requests")
    donor = relationship("Donor", back_populates="requests", foreign_keys=[donor_id])

class DemandHistory(Base):
    """Historical blood demand data for ML training"""
    __tablename__ = "demand_history"
    
    id = Column(Integer, primary_key=True, index=True)
    blood_type = Column(String(5), nullable=False, index=True)  # A+, B-, O+, etc.
    region = Column(String(100), nullable=False, index=True)  # Geographic region
    demand_units = Column(Integer, nullable=False)  # Number of units requested
    date = Column(DateTime, nullable=False, index=True)  # Date of demand
    season = Column(String(20), nullable=True, index=True)  # Winter, Summer, Monsoon, Post-Monsoon
    disease_outbreak = Column(Boolean, default=False, nullable=False)  # Whether there was disease outbreak
    created_at = Column(DateTime, server_default=func.now(), nullable=False)

class DemandForecast(Base):
    """Blood demand forecasts generated by ML model"""
    __tablename__ = "demand_forecasts"
    
    id = Column(Integer, primary_key=True, index=True)
    blood_type = Column(String(5), nullable=False, index=True)  # A+, B-, O+, etc.
    region = Column(String(100), nullable=False, index=True)  # Geographic region
    forecast_date = Column(DateTime, nullable=False, index=True)  # Date of forecast
    predicted_demand = Column(Float, nullable=False)  # Predicted demand in units
    confidence = Column(Float, nullable=False)  # Confidence score (0-1)
    shortage_risk = Column(String(20), nullable=False)  # Low, Medium, High, Critical
    alert_sent = Column(Boolean, default=False, nullable=False)  # Whether alert was sent
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

class InventoryLevel(Base):
    """Current blood inventory levels for redistribution logic"""
    __tablename__ = "inventory_levels"
    
    id = Column(Integer, primary_key=True, index=True)
    hospital_id = Column(Integer, ForeignKey("hospitals.id"), nullable=False, index=True)
    blood_type = Column(String(5), nullable=False, index=True)  # A+, B-, O+, etc.
    current_units = Column(Integer, nullable=False, default=0)  # Current stock level
    min_required = Column(Integer, nullable=False, default=10)  # Minimum required level
    max_capacity = Column(Integer, nullable=False, default=100)  # Maximum storage capacity
    last_updated = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # Relationships
    hospital = relationship("Hospital")

